### ISSUE TITLE
COCO results do not show

### ISSUE THREAD

**Issue by gguang10** [ozendelait/rvc_devkit#69]
We submitted COCO, but it doesn't show up on the list, can you please help us to operate it?
And why are the deadlines for the three tracks not the same, so that we can submit for MVD but not for COCO?

**Comment by gguang10** [comment]
And the deadline on the official website is 23h59 CEST/UTC+2 on October 3, why is COCO submission not allowed now?

**Comment by ozendelait** [comment]
Please post the username you use on CodaLabs and the method you are submitting here:
https://github.com/ozendelait/rvc_devkit/issues/66

**Comment by gguang10** [comment]
But we didn't fill in the method name when submitted. And we have another json, which is closed without time to submit, can I send it to you directly?

**Comment by tylin** [comment]
@gguang10 It looks like I made a mistake on the deadline. I edited the deadline and made it 23h59 CEST/UTC+2. Could you make the final submission to the evaluation server?

**Comment by gguang10** [comment]
Yes, many thanks.

**Comment by gguang10** [comment]
@tylin hi, the submission system is still not open and there is no submit button.

**Comment by ozendelait** [comment]
@gguang10 Please submit to all open servers and click on Show on Leaderboard so that the results are visible; If you are running into issues with one of the submission server before the deadline: 
Please upload your submission zip file to a file sharing website (e.g. https://wetransfer.com/ ) and send the generated link to me. Please do so before the end of the deadline.

**Comment by tylin** [comment]
@gguang10 Sorry it should work now.
