### ISSUE TITLE
RVC2022 Challenge Completed

### ISSUE THREAD

**Issue by ozendelait** [ozendelait/rvc_devkit#70]
**Thank you all for participating!** See you at the workshop on October 23rd. The program can be found here:
http://www.robustvision.net/index.php

All potential contestants are visible on http://www.robustvision.net/leaderboard.php (three incomplete entries might still be ranked if their submission/upload were before our deadline). 
If you think that your submission is missing, then please post here (including your method's name).

**Comment by AntiLibrary5** [comment]
Hi,
Our 3 individual submissions to the 3 benchmarks for Stereo were on time. 

Our method (CroCo_RVC is shown as incomplete for the moment). This is probably due to a typo in the name for the submission to Middlebury benchmark (we accidentally used "Croco_RVC" instead of "CroCo_RVC"). We are pretty sure this is the reason the crawler to have missed it. 

Since Middlebury does not allow editing from the user, is it possible to be able to take into account the results for Middlebury under the name "CroCo_RVC"? 
If not, we can try contacting the author of Middlebury benchmark to edit the name but we are not sure if that's possible either.

**Comment by ozendelait** [comment]
Thanks, all pending/incomplete submissions were verified (time of submission) and accepted. The leaderboard has been updated.

**Comment by ozendelait** [comment]
All winners and runner-ups have received instructions for their report/extended abstract to the email they registered with.
