### ISSUE TITLE
Questions regarding Technical Report (Size, Submission, Template)

### ISSUE THREAD

**Issue by qzed** [ozendelait/rvc_devkit#71]
Hi, we have three questions regarding the report:
- What length should the report have?
- Is there any template that we should use / is perferred?
- Where do we submit this report to? To you via your email address?

**Comment by ozendelait** [comment]
Yes, please send a pdf version of your report (1 or 2 pages, no special format/template/layout required) to my email address. 
It should include:
*) Data/Datasets used for training (supervised, semi-, and unsupervised)
*) Short summary of data augmentations used during training
*) Benchmark-specific steps you took for individual datasets during training and submission. If there are label mappings, a full list of intermediary labels and mappings to/from this space should be included or a public source with this information must be linked
*) A short paragraph on your methodology/differences vs. state of the art
*) A short paragraph about the biggest challenge met specifically when dealing with multiple leaderboards and data policies.
*) If there is a paper connected to the submission: a BibTeX entry
*) Include URLs if code is publicly available

**Comment by TomTomTommi** [comment]
Hi, will the report be published in the ECCV workshop? Besides, where can we find the report in 2020 or 2018?

**Comment by az-ja** [comment]
Hi, 
Is that OK if the report is longer than what you proposed?
It might not be so feasible to explain most parts in 2 pages.
Thank you for your time.

**Comment by ozendelait** [comment]
Please keep the report concise and concentrate on the aspects you think contributed most to winning at RVC. We have only a short timeframe to evaluate the reports so with too much content it is not feasable. So 2.5 pages is also fine but >3 will just be too much.

All winners & runner-ups announced during the workshop are invited to submit an extended version to the special Track 2 of our IJCV special issue. This will allow for more pages (at least 4; you can use more if the content is geared more towards Track1; i.e. focus on novelties for robustness instead of implementation details).

**Comment by ozendelait** [comment]
Yes, eventually the technical reports will be made public at robustvision.net.
We don't need to publish this right now, so if you have another publication in line we can delay individual report publications for up to 12 months.
